name: Deploy ke Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode dari repo
        uses: actions/checkout@v4

      - name: Instal Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instal Firebase Tools
        run: npm install -g firebase-tools

      # 🔑 Ambil Service Account dari secret dan tulis ke file
      - name: Tulis Service Account ke file JSON
        run: 'echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_APPTUADMIN }}" > ${GITHUB_WORKSPACE}/sa.json'

      # ⚙️ Jalankan deploy dengan kredensial itu
      - name: Deploy ke Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          firebase deploy --only hosting --non-interactive --project apptuadmin
